### ISSUE TITLE
Display STX/BTC Price per block for total miner commitment

### ISSUE THREAD

**Issue by saturnzenith** [friedger/pub-stacks-dump#4]
Based on the total miner commitment for the last block you can get the price in BTC which each STX token in the block reward was acquired for. See [https://discord.com/channels/621759717756370964/728030782693834862/803322823950336061](https://discord.com/channels/621759717756370964/728030782693834862/803322823950336061). 

This will be helpful to see how much of a discount miners are acquiring stx relative to retail price. 

This could be added in the dump.json [https://friedger.github.io/pub-stacks-dump/stacks-dump.json](https://friedger.github.io/pub-stacks-dump/stacks-dump.json)

**Comment by friedger** [comment]
price now displayed
