### ISSUE TITLE
Reduce amount of text output by stacks-dump

### ISSUE THREAD

**Issue by whoabuddy** [friedger/pub-stacks-dump#5]
Just [merged in some new options](https://github.com/psq/stacks-dump/commit/a337d39dad0745cfa1ccf5f63396606c088f58ed) for better control over the data output by stacks-node. The new options are also [in the readme.](https://github.com/psq/stacks-dump)

Do you think people are using the block data, or scrolling past it to see the table and statistics at the bottom?

The `-b` or `--no-blocks` option will not display individual block data so the miner stats table and statistics would be the main focus.

You can use `-l` or `--no-logo` if you wanted to shorten the output any further.

**Comment by friedger** [comment]
Probably, we should have both options. 
The list with all blocks should be paged, I guess.

**Comment by whoabuddy** [comment]
It's great for analysis, but thinking it's probably not the first thing people are looking for.

**Comment by friedger** [comment]
output is now limited to 1000 blocks, no logo
