### ISSUE TITLE
Output CSV version of results for review

### ISSUE THREAD

**Issue by whoabuddy** [friedger/pub-stacks-dump#6]
If you were to run stacks-dump a second time with `-l -c` then it would create a csv file that could be uploaded to the repo for each update, and linked from the website. 

It could also be used by other tools/services as things expand. I'd love to see more miners publishing their stacks-dump data.

**Comment by friedger** [comment]
Wouldn't the stacks-dump from other miners the same?

**Comment by whoabuddy** [comment]
I wonder about this, I know everything comes into eventual consistency, so probably only if you are on a fork or something is wrong.

I saw it more with the competition and a lot of the issues we experienced then have been fixed.

**Comment by friedger** [comment]
csv is now published
